image: samueldebruyn/debian-git

pipelines:
  tags: 
    'prod-*.*.*':             
      - step:
          name: Upload Files
          script:          
            - apt-get update
            - apt-get -qq install git-ftp
            # - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://185.201.11.216/ --remote-root public_html/ -vv --syncroot .
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://185.201.11.216/ --remote-root /public_html/ -vv --syncroot .
      
